### ISSUE TITLE
When exporting a single package, no project meta is created

### ISSUE THREAD

**Issue by isbm** [aplanas/obsgit#5]
After fixing another bug and anyhow firing this up (beware that in Ubuntu 20.04 `pygit2` is broken) I've exported a package from Factory. Importing it back to my `home:isbm` on OBS (public SUSE) resulted in "Project or package not found in build service". Creating a subproject e.g. `import` and pointing it out there also doesn't help.

Importing doesn't really work as well:

```
obsgit import /tmp/some_git_repo/ home:isbm:import
```

This results to the following:
```
Git LFS extension enabled in the repository
Traceback (most recent call last):
  File "./obsgit", line 1150, in <module>
    asyncio.run(args.func(args, config))
  File "/usr/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "./obsgit", line 1060, in import_
    await importer.project(project)
  File "./obsgit", line 741, in project
    await self.project_metadata(project)
  File "./obsgit", line 779, in project_metadata
    await asyncio.gather(
  File "./obsgit", line 784, in <genexpr>
    data=self.replace_project(metadata_path / meta, project),
  File "./obsgit", line 732, in replace_project
    with metadata_path.open() as f:
  File "/usr/lib/python3.8/pathlib.py", line 1213, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1069, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/some_git_repo/.obs/_meta'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ffa3bcb0dc0>
```

The `--package` flag also completely broken when importing.

@aplanas I thought you wanted Rust? :wink:

**Comment by aplanas** [comment]
The single package feature is a mechanism to aggregate packages from different projects, so there is already a project present. But I agree that starting exporting a single package without any project is a valid use case. This will take some defaults: https://github.com/aplanas/obsgit/commit/f60d8af7843ca79da84d66f1c4e2e85f34c60b84

**Comment by isbm** [comment]
If "The single package feature is a mechanism to aggregate packages from different projects" then it should stop and say "Please first the whole project first" instead of just crashing with a scary traceback.
