### ISSUE TITLE
Need a --don't-update-no-meta option for import 

### ISSUE THREAD

**Issue by coolo** [aplanas/obsgit#6]
Use case: 
 The git contains maintainer coolo because it's from my instance. Then @isbm imports it into his instance and removes coolo and adds himself as maintainer. 
 Now a 2nd update should not erase that. For new packages in git, yes - but no updates

**Comment by aplanas** [comment]
good one, on it.

**Comment by aplanas** [comment]
Done here: https://github.com/aplanas/obsgit/commit/2f290255889cbd8b281dd7ed0465185027ee11b2
