### ISSUE TITLE
obsgit create-config fails in gnome-terminal

### ISSUE THREAD

**Issue by mslacken** [aplanas/obsgit#9]
The command ``obsgit create-config`` fails in gnome-terminal (openSUSE Leap 15.2) with
```
Traceback (most recent call last):
  File "/usr/bin/obsgit", line 1172, in <module>
    "--username", "-u", default=os.getlogin(), help="username for login",
FileNotFoundError: [Errno 2] No such file or directory
```
Seems more likely a bug in python3 or gnome-terminal.
As workaround one can use an xterm instead.

**Comment by aplanas** [comment]
is this the full traceback? As you say can be a bug in python3 or gnome terminal, but I suspect that is happening inside os.getlogin(), so there will be more deeper information in the exception.
